<h2><?php echo $this->displayCurrentDate(); ?></h2>
<input type="text" id='playerName' placeholder='Name'>
<br>
<input type="button" id='save' value='Spieler eingeben'>
<input type="button" id='start' value='Start 1vs1 Turnier' hidden='true' >
<input type="button" id='start2v2' value='Start 2vs2 Turnier' hidden='true'><br>
<input type="button" id='restart' value='Zuruecksetzen'><br>
<input type="text" id='matchnummber' placeholder='Spielnummer' hidden='true'>
<input type="text" id='winnerName' placeholder='Gewinner' hidden='true'>
<input type="button" id='matchreload' value='Senden' hidden='true'>
<div id='teams' hidden='true'></div>
<div id='member'>
    <span>SpielerAnzahl</span>
    <div id='spielerAnzahl'></div>
    </div><br>
<div id='table'></div>

<script type="text/javascript">
    playerArray = [];
    winnerArray = [];
    trnumber = 0;
    counter = 0;
    tableTree='';
    id = 0;
    spalte1 = 1;
    spalte2 = 0;
    $('#matchreload').click(function(){
        var matchNummber = $('#matchnummber').val();
        var matchWinner = $('#winnerName').val();
        if(playerArray.indexOf(matchWinner)>=0 ||stringTeams.indexOf(matchWinner)>=0){
            $('#winner'+matchNummber+'').html(matchWinner);
        }
        })
    $('#restart').click(function(){
        $('#start').hide();
        $('#save').show();
        playerArray = [];
        counter = 0;
        id = 0;
        spalte1 = 1;
        spalte2 = 0;
        $('#spielerAnzahl').html(counter);
        $('#table').html('');
        $('#playerName').show();
        $('#playerName').val('');
        $('#member').show();
        $('#matchnummber').hide();
        $('#winnerName').hide();
        $('#matchreload').hide();
        $('#start2v2').hide();
        $('#teams').hide();
        $('#teams').html('');
        })
    $('#save').click(function(){
        if($('#playerName').val()!=''){
            playerArray.push($('#playerName').val());
            $('#playerName').val('');
            counter++;
            $('#spielerAnzahl').html(counter);
            if(counter>=4){
                $('#start').show();
                if(counter%2 == 0){
                    $('#start2v2').show();
                }else{
                    $('#start2v2').hide();
                }
            }
        }else{
            alert('Name eingeben!');
        }
    })
     $('#start').click(function(){
         $('#save').hide();
         $('#playerName').hide();
         $('#matchnummber').show();
         $('#winnerName').show();
         $('#member').hide();
         $('#matchreload').show();
         tableTree = '';
         playerArray = shuffle(playerArray);
         tableTree += '<table>';
         for(var i = 0 ; i < (counter*2)-1 ; i++){
             if(i % 2 != 0){
                tableTree +='<tr id='+trnumber+'>'
                if(spalte1 == 2){
                    tableTree +='<td></td>'
                    }
                if(spalte1 == 4){
                    tableTree +='<td></td>'
                    tableTree +='<td></td>'
                    spalte1 = 0;
                    spalte2 ++;
                }
                if(spalte2 == 2){
                    tableTree +='<td></td>'
                    spalte1 = 0;
                    spalte2 = 0;
                }
                tableTree +='<td>VS'+id+'</td>'
                tableTree +='<td id="winner'+id+'">Gewinner</td>'
                tableTree +='</tr>'
                spalte1++
            }else{
                tableTree +='<tr id='+trnumber+'>'
                    tableTree +='<td id="fighter'+id+'">'+playerArray[id]+'</td>'
                tableTree +='</tr>'
            id++;
            }
             trnumber++;
         }
         tableTree += '</table>';
         $('#table').append(tableTree);

     })
     function shuffle(array) {
        var currentIndex = array.length
        , temporaryValue
        , randomIndex
        ;

        while (0 !== currentIndex) {

            randomIndex = Math.floor(Math.random() * currentIndex);
            currentIndex -= 1;

            temporaryValue = array[currentIndex];
            array[currentIndex] = array[randomIndex];
            array[randomIndex] = temporaryValue;
        }

     return array;
     }
    $('#start2v2').click(function(){
        $('#save').hide();
        $('#playerName').hide();
        $('#matchnummber').show();
        $('#winnerName').show();
        $('#member').hide();
        $('#start2v2').hide();
        $('#start').hide();
        $('#matchreload').show();
        $('#teams').show();
        stringTeams = '';
        for(var i = 0; i < 2; i++){
            playerArray = shuffle(playerArray);
        }
        tempArray=[];
        var i,j,chunk = 2;
        for (i=0,j=playerArray.length; i<j; i+=chunk) {
            tempArray.push( playerArray.slice(i,i+chunk));
        }
        for(var i = 0; i < 2; i++){
            tempArray = shuffle(tempArray);
        }
        for(i = 0; i < tempArray.length; i++){
            stringTeams += 'Team'+(i+1)+': '+ tempArray[i] + '<br>';
            }
        $('#teams').append(stringTeams);
        tableTree = '';
        tableTree += '<table>';
        for(var i = 0 ; i < (counter)-1 ; i++){
            if(i % 2 != 0){
               tableTree +='<tr id='+trnumber+'>'
               if(spalte1 == 2){
                   tableTree +='<td></td>'
                   }
               if(spalte1 == 4){
                   tableTree +='<td></td>'
                   tableTree +='<td></td>'
                   spalte1 = 0;
                   spalte2 ++;
               }
               if(spalte2 == 2){
                   tableTree +='<td></td>'
                   spalte1 = 0;
                   spalte2 = 0;
               }
               tableTree +='<td>VS'+id+'</td>'
               tableTree +='<td id="winner'+id+'">Gewinner</td>'
               tableTree +='</tr>'
               spalte1++
           }else{
               tableTree +='<tr id='+trnumber+'>'
                   tableTree +='<td id="fighter'+id+'">Team'+[id+1]+'</td>'
               tableTree +='</tr>'
           id++;
           }
            trnumber++;
        }
        tableTree += '</table>';
        $('#table').append(tableTree);
    })

</script>